name: Scan with local scanner

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  workflow_run:
      workflows: [Contrast Security App Workflow]
      types: [completed]
      branches: [DEV-569]


permissions:
  contents: read
  checks: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: DEV-569
      - uses: marklacasse/contrast-local-scan-action@
      Contrast-Security-OSS/contrast-local-scan-action@fixdownload
        with:
          apiUrl: ${{ secrets.CONTRAST__API__URL }}
          apiUserName: ${{ secrets.CONTRAST__API__USER_NAME }}
          apiKey: ${{ secrets.CONTRAST__API__API_KEY }}
          apiServiceKey: ${{ secrets.CONTRAST__API__SERVICE_KEY }}
          apiOrgId: ${{ secrets.CONTRAST__API__ORGANIZATION }}
          resourceGroup: CICD-Test
          projectName: GithubA-DjanGoat2
          checks: false
          label: "Github Action Scan (${{ github.actor }} / Testing)"
          # severity: low
          timeout: 360
          path: "./"


